import { StyleSheet } from 'react-native';

// Changing the color scheme from Zomato's red to Zepto's purple
const colors = {
  primary: '#8428FF', // Zepto purple
  primaryLight: '#A35FFF', // Lighter shade of purple
  primaryDark: '#6200EA', // Darker shade of purple
  background: '#f9f9f9',
  white: '#ffffff',
  dark: '#222222',
  gray: '#7a7a7a',
  lightGray: '#eeeeee',
  success: '#00C853',
  rating: '#5B51D8', // Zepto rating color (purple-blue)
  border: '#e5e5e5',
  accent: '#F4F0FF' // Light purple for backgrounds/accents
};

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.background,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: colors.white,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    elevation: 2,
  },
  backButton: {
    padding: 8,
  },
  headerTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.dark,
  },
  headerPlaceholder: {
    width: 32,
  },
  content: {
    flex: 1,
  },
  section: {
    marginBottom: 16,
    paddingHorizontal: 16,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 8,
    marginTop: 16,
    color: colors.dark,
  },
  orderDetailsCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  orderTypeText: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 4,
    color: colors.dark,
  },
  deliveryDetailsText: {
    fontSize: 14,
    color: colors.gray,
    marginBottom: 12,
  },
  divider: {
    height: 1,
    backgroundColor: colors.border,
    marginVertical: 12,
  },
  orderItemsTitle: {
    fontSize: 15,
    fontWeight: '600',
    marginBottom: 12,
    color: colors.dark,
  },
  orderItemRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  orderItemName: {
    flex: 1,
    fontSize: 14,
    color: colors.dark,
  },
  orderItemQuantity: {
    fontSize: 14,
    color: colors.gray,
    width: 28,
    textAlign: 'center',
  },
  orderItemPrice: {
    fontSize: 14,
    fontWeight: '600',
    width: 60,
    textAlign: 'right',
    color: colors.dark,
  },
  moreItemsText: {
    fontSize: 13,
    color: colors.primary,
    marginTop: 8,
    fontWeight: '600',
  },
  priceSummary: {
    marginTop: 6,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  priceLabel: {
    fontSize: 14,
    color: colors.gray,
  },
  priceValue: {
    fontSize: 14,
    fontWeight: '500',
    color: colors.dark,
  },
  savingsLabel: {
    fontSize: 14,
    color: colors.success,
  },
  savingsValue: {
    fontSize: 14,
    fontWeight: '600',
    color: colors.success,
  },
  totalRow: {
    marginTop: 8,
    paddingTop: 8,
    borderTopWidth: 1,
    borderTopColor: colors.border,
  },
  totalLabel: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.dark,
  },
  totalValue: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.dark,
  },
  addressCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  addressRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  addressIcon: {
    marginRight: 10,
    marginTop: 2,
    color: colors.primary,
  },
  addressText: {
    flex: 1,
    fontSize: 14,
    lineHeight: 20,
    color: colors.dark,
  },
  editButton: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 10,
  },
  editButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.primary,
    marginLeft: 4,
  },
  paymentMethodCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 14,
    marginHorizontal: 16,
    marginBottom: 10,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  paymentMethodCardSelected: {
    borderWidth: 1.5,
    borderColor: colors.primary,
    backgroundColor: colors.accent,
  },
  paymentMethodIcon: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: colors.lightGray,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  iconText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.dark,
  },
  paymentMethodTitle: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: colors.dark,
  },
  checkmark: {
    width: 20,
    height: 20,
    alignItems: 'center',
    justifyContent: 'center',
    color: colors.primary,
  },
  payButtonContainer: {
    padding: 16,
    paddingBottom: 24,
    backgroundColor: colors.white,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    elevation: 4,
  },
  payButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.primary,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
  },
  payButtonProcessing: {
    backgroundColor: colors.gray,
  },
  payButtonComplete: {
    backgroundColor: colors.success,
  },
  payButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: colors.white,
    marginRight: 6,
  },
  securityNote: {
    fontSize: 12,
    color: colors.gray,
    textAlign: 'center',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
    justifyContent: 'flex-end',
  },
  modalContent: {
    backgroundColor: colors.white,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    padding: 20,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: colors.dark,
  },
  closeButton: {
    padding: 6,
  },
  modalBody: {
    marginBottom: 16,
  },
  inputGroup: {
    marginBottom: 14,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: '600',
    marginBottom: 8,
    color: colors.dark,
  },
  input: {
    backgroundColor: colors.background,
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    minHeight: 100,
    textAlignVertical: 'top',
    color: colors.dark,
    borderWidth: 1,
    borderColor: colors.border,
  },
  modalFooter: {
    marginTop: 8,
  },
  saveButton: {
    backgroundColor: colors.primary,
    borderRadius: 12,
    padding: 14,
    alignItems: 'center',
  },
  saveButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: colors.white,
  },
  paymentGatewayBadge: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 10,
    marginBottom: 10,
    backgroundColor: colors.accent,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  paymentGatewayText: {
    fontSize: 12,
    color: colors.primary,
    marginLeft: 6,
    fontWeight: '600',
  },
  loadingContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background,
  },
  loadingText: {
    fontSize: 14,
    color: colors.gray,
    marginTop: 12,
  },
  userInfoCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  userGreeting: {
    fontSize: 16,
    fontWeight: '700',
    marginBottom: 2,
    color: colors.dark,
  },
  userEmail: {
    fontSize: 13,
    color: colors.gray,
  },
  paymentInfoCard: {
    backgroundColor: colors.white,
    borderRadius: 12,
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.03,
    shadowRadius: 3,
    elevation: 1,
  },
  paymentInfoText: {
    fontSize: 13,
    color: colors.dark,
    marginBottom: 10,
    lineHeight: 18,
  },
  webViewHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.white,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
    height: 52,
    elevation: 2,
  },
  webViewBackButton: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 6,
  },
  webViewBackText: {
    fontSize: 14,
    color: colors.primary,
    marginLeft: 4,
    fontWeight: '600',
  },
  webViewTitle: {
    flex: 1,
    fontSize: 16,
    fontWeight: '700',
    textAlign: 'center',
    marginRight: 32, // To balance the back button
    color: colors.dark,
  },
  // Zepto specific styles
  ratingBadge: {
    backgroundColor: colors.rating,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: 4,
    alignSelf: 'flex-start',
  },
  ratingText: {
    color: colors.white,
    fontSize: 11,
    fontWeight: '700',
  },
  offerTag: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 6,
    paddingHorizontal: 8,
    backgroundColor: '#F0F7FF',
    borderRadius: 6,
    marginBottom: 10,
    borderLeftWidth: 3,
    borderLeftColor: colors.primary,
  },
  offerText: {
    fontSize: 12,
    color: colors.primary,
    marginLeft: 6,
    fontWeight: '600',
  },
  // New Zepto-specific styles
  deliveryTimeCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.accent,
    borderRadius: 10,
    paddingVertical: 8,
    paddingHorizontal: 12,
    marginBottom: 12,
  },
  deliveryTimeText: {
    color: colors.primary,
    fontSize: 13,
    fontWeight: '600',
    marginLeft: 6,
  },
  zapLogo: {
    width: 18,
    height: 18,
    marginRight: 6,
  },
  quickDeliveryTag: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F0FFF0',
    paddingVertical: 4,
    paddingHorizontal: 8,
    borderRadius: 4,
    alignSelf: 'flex-start',
    marginBottom: 8,
  },
  quickDeliveryText: {
    color: '#2E7D32',
    fontSize: 11,
    fontWeight: '600',
  }
});

// Adding default export to satisfy the routing system
export default function PaymentsStyles() {
  return null;
}